---
dates_list:

  - field: byDateTab
    by: id
    actions:
      - action: click

  - field: date
    by: class_name
    meta:
      - multiple
    actions:
      - action: unpack
        children:

          - field: h3.date-title.highlight-foreground
            by: css_selector
            meta:
              - optional
            actions:
              - action: get_asset
                name: date
                method: get_attribute
                field: innerHTML
                special:
                  method: convert_date
                  format: "%A %d, %B %Y"

          - field: "film "
            by: class_name
            meta:
              - multiple
            actions:
              - action: unpack
                children:

                  - field: h3.title
                    by: css_selector
                    actions:
                      - action: get_asset
                        name: title
                        method: get_attribute
                        field: innerHTML

                  - field: censor
                    by: class_name
                    actions:
                      - action: get_asset
                        name: rating
                        method: text_member

                  - field: poster
                    by: class_name
                    actions:
                      - action: save_poster
                        name: poster
                        method: get_attribute
                        field: "alt"

                  - field: ".session-times li"
                    by: css_selector
                    meta:
                      - multiple
                    actions:
                      - action: unpack
                        children:

                          - field: tickets-sold-out
                            by: class_name
                            meta:
                              - optional
                            actions:
                              - action: get_asset
                                name: available
                                method: text_member

                          - field: a
                            by: tag_name
                            actions:
                              - action: get_asset
                                name: link
                                method: get_attribute
                                field: "href"

                          - field: time
                            by: tag_name
                            actions:
                              - action: get_asset
                                name: time
                                method: text_member
                                special:
                                  method: convert_time
                                  format: "%I:%M %p"
                              - action: create_showing

              - action: create_listing  # For each film
